version: '2.1'

services:
  kong-database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up

  kong:
    build: .
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_started
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_LOG_LEVEL=info
      - KONG_PROXY_ERROR_LOG='/dev/stdout'
      - KONG_PROXY_ACCESS_LOG='/dev/stdout'
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
    expose:
      - 8000
      - 8001

  kong-dashboard:
    image: pgbi/kong-dashboard:v3.5.0

    depends_on:
      kong:
        condition: service_started
    command: "start --kong-url http://kong:8001"
    ports:
      - 8080:8080
    expose:
      - 8080
